<a href="https://colab.research.google.com/github/ayannj13/Data-Science/blob/main/Homework6_AyanJamal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Intro
Term deposits are a major source of income for a bank. A term deposit is a cash investment held at a financial institution. Your money is invested for an agreed rate of interest over a fixed amount of time, or term. The bank has various outreach plans to sell term deposits to their customers such as email marketing, advertisements, telephonic marketing, and digital marketing.

Telephonic marketing campaigns still remain one of the most effective way to reach out to people. However, they require huge investment as large call centers are hired to actually execute these campaigns. Hence, it is crucial to identify the customers most likely to convert beforehand so that they can be specifically targeted via call.

The data is related to direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe to a term deposit (variable y).

Content
The data is related to the direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed by the customer or not. The data folder contains two datasets:-

Bank.csv: 45,211 rows and 18 columns ordered by date (from May 2008 to November 2010)

Detailed Column Descriptions
bank client data:

1 - age (numeric)

2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
"blue-collar","self-employed","retired","technician","services")

3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)

4 - education (categorical: "unknown","secondary","primary","tertiary")

5 - default: has credit in default? (binary: "yes","no")

6 - balance: average yearly balance, in euros (numeric)

7 - housing: has housing loan? (binary: "yes","no")

8 - loan: has personal loan? (binary: "yes","no")
# related with the last contact of the current campaign:
9 - contact: contact communication type (categorical: "unknown","telephone","cellular")
10 - day: last contact day of the month (numeric)

11 - month: last contact month of year (categorical: "jan", "feb", "mar", …, "nov", "dec")

12 - duration: last contact duration, in seconds (numeric)

# other attributes:
13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)

14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)

15 - previous: number of contacts performed before this campaign and for this client (numeric)

16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")

Output variable (desired target):

17 - y - has the client subscribed a term deposit? (binary: "yes","no")

Missing Attribute Values: None


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/Bank.csv',sep = ';')
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [2]:
print(df.shape)
df.info()
df.isnull().sum()

(45211, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [3]:
#For object check the data
for cn in df.columns:
  if(df[cn].dtype==object):
    print(df[cn].value_counts())


job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64
marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64
education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64
default
no     44396
yes      815
Name: count, dtype: int64
housing
yes    25130
no     20081
Name: count, dtype: int64
loan
no     37967
yes     7244
Name: count, dtype: int64
contact
cellular     29285
unknown      13020
telephone     2906
Name: count, dtype: int64
month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: count, dtype: int64
poutcome
unknown    36959
failure     4901
other  

In [4]:
# Following function converts non-numeric variables (e.g., 'category', 'object') into numeric using label encoding
# Note:
#Label encoding converts categorical values into integer codes. Each unique category is assigned a distinct number, such as 1, 2, 3, 4, etc.
#Example : In our data, education variable has following values:{ 'primary' 'secondary', 'tertiary', 'unknown'}
#and it is mapped { 'primary': 0, 'secondary': 1, 'tertiary': 2, 'unknown': 3}

#  education  education_encoded
#  secondary                  1
#   tertiary                  2
#    primary                  0
#    unknown                  3
#   tertiary                  2
#    primary                  0
#
#Label encoding is generally suitable for tree-based models (e.g., decision trees, random forests, boosting methods).
#However, it may not be appropriate for models where the objective function relies on distance-based calculations, such as neural networks, support vector machines (SVM), or linear regression.
#For nominal features (categories with no intrinsic ordering, e.g., "red," "blue," "green"), label encoding can mislead the model by implying an ordinal relationship where none exists.
#In such cases, one-hot encoding is usually preferred.
#One-hot encoding creates binary columns (dummy variables) for each category in a categorical feature, avoiding the introduction of unintended ordinality.

def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df


In [5]:
df=Encoder(df)
df

age  job  marital  education  default  balance  housing  loan  contact  \
0       58    4        1          2        0     2143        1     0        2   
1       44    9        2          1        0       29        1     0        2   
2       33    2        1          1        0        2        1     1        2   
3       47    1        1          3        0     1506        1     0        2   
4       33   11        2          3        0        1        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
45206   51    9        1          2        0      825        0     0        0   
45207   71    5        0          0        0     1729        0     0        0   
45208   72    5        1          1        0     5715        0     0        0   
45209   57    1        1          1        0      668        0     0        1   
45210   37    2        1          1        0     2971        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  y  
0        5      8       261         1     -1         0         3  0  
1        5      8       151         1     -1         0         3  0  
2        5      8        76         1     -1         0         3  0  
3        5      8        92         1     -1         0         3  0  
4        5      8       198         1     -1         0         3  0  
...    ...    ...       ...       ...    ...       ...       ... ..  
45206   17      9       977         3     -1         0         3  1  
45207   17      9       456         2     -1         0         3  1  
45208   17      9      1127         5    184         3         2  1  
45209   17      9       508         4     -1         0         3  0  
45210   17      9       361         2    188        11         1  0  

[45211 rows x 17 columns]

In [6]:
y = df['y'] #Output
X = df.drop('y',axis=1)
X

age  job  marital  education  default  balance  housing  loan  contact  \
0       58    4        1          2        0     2143        1     0        2   
1       44    9        2          1        0       29        1     0        2   
2       33    2        1          1        0        2        1     1        2   
3       47    1        1          3        0     1506        1     0        2   
4       33   11        2          3        0        1        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
45206   51    9        1          2        0      825        0     0        0   
45207   71    5        0          0        0     1729        0     0        0   
45208   72    5        1          1        0     5715        0     0        0   
45209   57    1        1          1        0      668        0     0        1   
45210   37    2        1          1        0     2971        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  
0        5      8       261         1     -1         0         3  
1        5      8       151         1     -1         0         3  
2        5      8        76         1     -1         0         3  
3        5      8        92         1     -1         0         3  
4        5      8       198         1     -1         0         3  
...    ...    ...       ...       ...    ...       ...       ...  
45206   17      9       977         3     -1         0         3  
45207   17      9       456         2     -1         0         3  
45208   17      9      1127         5    184         3         2  
45209   17      9       508         4     -1         0         3  
45210   17      9       361         2    188        11         1  

[45211 rows x 16 columns]

In [7]:
from sklearn.model_selection import  train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)




Q1)Using  Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate Accuracy on Test data. Which method gives the best accuracy on test data

In [8]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score

# Random Forest
rf = RandomForestClassifier(random_state=17)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)

# Gradient Boosting
gb = GradientBoostingClassifier(random_state=17)
gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)
gb_acc = accuracy_score(y_test, gb_pred)

# XGBoost
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state=17, use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
xgb_acc = accuracy_score(y_test, xgb_pred)

# LightGBM
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=17)
lgb.fit(X_train, y_train)
lgb_pred = lgb.predict(X_test)
lgb_acc = accuracy_score(y_test, lgb_pred)

# Print all accuracies
print("Random Forest Accuracy:", rf_acc)
print("Gradient Boosting Accuracy:", gb_acc)
print("XGBoost Accuracy:", xgb_acc)
print("LightGBM Accuracy:", lgb_acc)

# Best model
best_model = max(
    [('Random Forest', rf_acc), ('Gradient Boosting', gb_acc),
     ('XGBoost', xgb_acc), ('LightGBM', lgb_acc)],
    key=lambda x: x[1]
)
print(f"\n✅ Best performing model: {best_model[0]} with accuracy: {best_model[1]:.4f}")


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [09:54:15] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[LightGBM] [Info] Number of positive: 3940, number of negative: 29968
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004556 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 988
[LightGBM] [Info] Number of data points in the train set: 33908, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116197 -> initscore=-2.028949
[LightGBM] [Info] Start training from score -2.028949
Random Forest Accuracy: 0.9025037600636999
Gradient Boosting Accuracy: 0.9018844554543042
XGBoost Accuracy: 0.9036538971954349
LightGBM Accuracy: 0.9073697248518092

✅ Best performing model: LightGBM with accuracy: 0.9074


**Q1**: Best model is LightGBM, as it achieved the highest - 90.74% test accuracy.

Q2) Using optuna hyperparmeter optimization technique and 100 trial

 a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation accuracy?
 For random forest


  "max_depth"   : trial.suggest_int("max_depth", 2,  X_train.shape[1]),
  "max_features": trial.suggest_int("max_features", 2, X_train.shape[1])

For XGBoost, Light GBM and Gradient Boosting Classifier

  "max_depth": trial.suggest_int("max_depth", 2, X_train.shape[1]),
  "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.3,log=True)

where X_train.shape[1] is number of columnns in the train data.

 b)Evaluate the performance of the  method with highest cross validation accuracy on test data.What is the accuracy value? Are there any improvement of the same method with default parameters?


In [9]:
!pip install optuna --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 13.5 MB/s eta 0:00:00


In [10]:
#Q2 a)
#importing libraries

import optuna
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import numpy as np

In [11]:
#Random forest
def rf_objective(trial):
    max_depth = trial.suggest_int("max_depth", 2, X_train.shape[1])
    max_features = trial.suggest_int("max_features", 2, X_train.shape[1])

    model = RandomForestClassifier(
        max_depth=max_depth,
        max_features=max_features,
        random_state=17
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy')
    return score.mean()

In [12]:
#Gradient Boosting
def gb_objective(trial):
    max_depth = trial.suggest_int("max_depth", 2, X_train.shape[1])
    learning_rate = trial.suggest_float("learning_rate", 0.001, 0.3, log=True)

    model = GradientBoostingClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        random_state=17
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy')
    return score.mean()


In [13]:
#Xgboost
def xgb_objective(trial):
    max_depth = trial.suggest_int("max_depth", 2, X_train.shape[1])
    learning_rate = trial.suggest_float("learning_rate", 0.001, 0.3, log=True)

    model = XGBClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        use_label_encoder=False,
        eval_metric='logloss',
        random_state=17
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy')
    return score.mean()

In [14]:
#LightGBM
def lgb_objective(trial):
    max_depth = trial.suggest_int("max_depth", 2, X_train.shape[1])
    learning_rate = trial.suggest_float("learning_rate", 0.001, 0.3, log=True)

    model = LGBMClassifier(
        max_depth=max_depth,
        learning_rate=learning_rate,
        random_state=17
    )

    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy')
    return score.mean()

In [15]:
#running optuna
study_rf = optuna.create_study(direction="maximize")
study_rf.optimize(rf_objective, n_trials=100)

study_gb = optuna.create_study(direction="maximize")
study_gb.optimize(gb_objective, n_trials=100)

study_xgb = optuna.create_study(direction="maximize")
study_xgb.optimize(xgb_objective, n_trials=100)

study_lgb = optuna.create_study(direction="maximize")
study_lgb.optimize(lgb_objective, n_trials=100)

[I 2025-04-13 10:03:07,027] A new study created in memory with name: no-name-a0f5c727-b597-4595-a869-03ccfa8b79db
[I 2025-04-13 10:03:11,488] Trial 0 finished with value: 0.8939778360748277 and parameters: {'max_depth': 6, 'max_features': 3}. Best is trial 0 with value: 0.8939778360748277.
[I 2025-04-13 10:03:35,554] Trial 1 finished with value: 0.9044178450302717 and parameters: {'max_depth': 9, 'max_features': 14}. Best is trial 1 with value: 0.9044178450302717.
[I 2025-04-13 10:04:00,056] Trial 2 finished with value: 0.9047717960025198 and parameters: {'max_depth': 13, 'max_features': 10}. Best is trial 2 with value: 0.9047717960025198.
[I 2025-04-13 10:04:11,527] Trial 3 finished with value: 0.9044768629523222 and parameters: {'max_depth': 8, 'max_features': 9}. Best is trial 2 with value: 0.9047717960025198.
[I 2025-04-13 10:04:31,054] Trial 4 finished with value: 0.9044178450302717 and parameters: {'max_depth': 9, 'max_features': 14}. Best is trial 2 with value: 0.904771796002519

[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002841 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002857 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:10:53,377] Trial 0 finished with value: 0.9053025893848452 and parameters: {'max_depth': 15, 'learning_rate': 0.02441263819093759}. Best is trial 0 with value: 0.9053025893848452.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002846 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002699 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:10:54,579] Trial 1 finished with value: 0.905921956618263 and parameters: {'max_depth': 16, 'learning_rate': 0.23514223759893044}. Best is trial 1 with value: 0.905921956618263.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002824 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002732 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:10:55,972] Trial 2 finished with value: 0.8914415527471778 and parameters: {'max_depth': 9, 'learning_rate': 0.011103408101844866}. Best is trial 1 with value: 0.905921956618263.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002795 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002722 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:10:57,272] Trial 3 finished with value: 0.8838032329432165 and parameters: {'max_depth': 10, 'learning_rate': 0.0032378489025534293}. Best is trial 1 with value: 0.905921956618263.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002831 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002861 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:10:58,538] Trial 4 finished with value: 0.9073670346281982 and parameters: {'max_depth': 15, 'learning_rate': 0.17056040823740326}. Best is trial 4 with value: 0.9073670346281982.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002804 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002718 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:10:59,994] Trial 5 finished with value: 0.9082812227104409 and parameters: {'max_depth': 15, 'learning_rate': 0.05239962673645042}. Best is trial 5 with value: 0.9082812227104409.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002784 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

[I 2025-04-13 11:11:01,800] Trial 6 finished with value: 0.8997582368319333 and parameters: {'max_depth': 5, 'learning_rate': 0.020378004741128997}. Best is trial 5 with value: 0.9082812227104409.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosin

[I 2025-04-13 11:11:03,204] Trial 7 finished with value: 0.9046538201731066 and parameters: {'max_depth': 4, 'learning_rate': 0.08507156855960922}. Best is trial 5 with value: 0.9082812227104409.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[I 2025-04-13 11:11:04,021] Trial 8 finished with value: 0.8838032329432165 and parameters: {'max_depth': 3, 'learning_rate': 0.00124888156861582}. Best is trial 5 with value: 0.9082812227104409.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002819 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002748 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:05,318] Trial 9 finished with value: 0.8838032329432165 and parameters: {'max_depth': 15, 'learning_rate': 0.002067064057008681}. Best is trial 5 with value: 0.9082812227104409.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002808 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002772 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:06,771] Trial 10 finished with value: 0.9078978462758635 and parameters: {'max_depth': 11, 'learning_rate': 0.05205065023436333}. Best is trial 5 with value: 0.9082812227104409.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002855 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002814 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:08,193] Trial 11 finished with value: 0.9082517685454349 and parameters: {'max_depth': 11, 'learning_rate': 0.06442790584890268}. Best is trial 5 with value: 0.9082812227104409.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002803 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002880 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:09,639] Trial 12 finished with value: 0.9086056516749924 and parameters: {'max_depth': 12, 'learning_rate': 0.060251879695890825}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002885 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002811 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:11,040] Trial 13 finished with value: 0.8839801849453323 and parameters: {'max_depth': 13, 'learning_rate': 0.007659597780780734}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002792 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002786 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:12,484] Trial 14 finished with value: 0.9063938025305626 and parameters: {'max_depth': 7, 'learning_rate': 0.03471471196988715}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002688 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003949 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:14,287] Trial 15 finished with value: 0.9074555249805946 and parameters: {'max_depth': 13, 'learning_rate': 0.12737205033402435}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002846 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:15,937] Trial 16 finished with value: 0.8839506942496467 and parameters: {'max_depth': 13, 'learning_rate': 0.007215607273809079}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002840 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002830 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:17,385] Trial 17 finished with value: 0.9070720702659897 and parameters: {'max_depth': 7, 'learning_rate': 0.04635458582642965}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002700 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002845 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:18,726] Trial 18 finished with value: 0.9077209281950928 and parameters: {'max_depth': 12, 'learning_rate': 0.10778761507785327}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002678 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002824 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:19,955] Trial 19 finished with value: 0.9047127702524665 and parameters: {'max_depth': 8, 'learning_rate': 0.2816405432932658}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002836 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points 

[I 2025-04-13 11:11:21,411] Trial 20 finished with value: 0.8958358386203794 and parameters: {'max_depth': 14, 'learning_rate': 0.015130303509542068}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002766 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002839 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:22,884] Trial 21 finished with value: 0.9081337770600161 and parameters: {'max_depth': 11, 'learning_rate': 0.0440260476769109}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002800 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002845 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:24,267] Trial 22 finished with value: 0.9085761661979754 and parameters: {'max_depth': 11, 'learning_rate': 0.08244650883551981}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002786 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002748 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:25,900] Trial 23 finished with value: 0.9080158090586053 and parameters: {'max_depth': 12, 'learning_rate': 0.08342595262363596}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003977 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003951 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:27,861] Trial 24 finished with value: 0.9056859788660939 and parameters: {'max_depth': 16, 'learning_rate': 0.027897697438642732}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002720 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002806 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`

[I 2025-04-13 11:11:29,212] Trial 25 finished with value: 0.9073375413231785 and parameters: {'max_depth': 9, 'learning_rate': 0.1317079276556743}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002716 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002764 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:30,644] Trial 26 finished with value: 0.9083992220238623 and parameters: {'max_depth': 10, 'learning_rate': 0.06827486711992602}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002844 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002754 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:31,911] Trial 27 finished with value: 0.9065117679226389 and parameters: {'max_depth': 10, 'learning_rate': 0.1796101600784516}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002814 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002866 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`

[I 2025-04-13 11:11:33,317] Trial 28 finished with value: 0.9071605736650571 and parameters: {'max_depth': 6, 'learning_rate': 0.07894386854028558}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002939 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002816 seconds.
You can set `force_row_wise=true` to remove t

[I 2025-04-13 11:11:34,804] Trial 29 finished with value: 0.9065412168689764 and parameters: {'max_depth': 10, 'learning_rate': 0.029295228367431654}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002847 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002748 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:36,253] Trial 30 finished with value: 0.896012777575824 and parameters: {'max_depth': 12, 'learning_rate': 0.01524229428500862}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002819 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003959 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:37,829] Trial 31 finished with value: 0.9075439527089687 and parameters: {'max_depth': 14, 'learning_rate': 0.05706788163023876}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003957 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004063 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points 

[I 2025-04-13 11:11:39,700] Trial 32 finished with value: 0.9058924372199005 and parameters: {'max_depth': 8, 'learning_rate': 0.18058107212665214}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004023 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002883 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:41,269] Trial 33 finished with value: 0.9073080454088244 and parameters: {'max_depth': 16, 'learning_rate': 0.037114146212882455}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002709 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002831 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:42,619] Trial 34 finished with value: 0.9074850026296087 and parameters: {'max_depth': 14, 'learning_rate': 0.1072350025526857}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002795 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002729 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:44,046] Trial 35 finished with value: 0.9077208760084079 and parameters: {'max_depth': 10, 'learning_rate': 0.07267945638491627}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002702 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002742 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:45,510] Trial 36 finished with value: 0.9028252744018951 and parameters: {'max_depth': 12, 'learning_rate': 0.02039889082242823}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002695 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002740 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:46,742] Trial 37 finished with value: 0.9053321374858841 and parameters: {'max_depth': 15, 'learning_rate': 0.20339475806542687}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002840 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

[I 2025-04-13 11:11:47,553] Trial 38 finished with value: 0.9012033226698715 and parameters: {'max_depth': 2, 'learning_rate': 0.10275631591381301}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002730 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:48,959] Trial 39 finished with value: 0.8905568110019385 and parameters: {'max_depth': 9, 'learning_rate': 0.01045962119727272}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002822 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002863 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:50,457] Trial 40 finished with value: 0.9069836660216236 and parameters: {'max_depth': 11, 'learning_rate': 0.14011592930338038}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003977 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004094 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:52,546] Trial 41 finished with value: 0.9073080375808217 and parameters: {'max_depth': 11, 'learning_rate': 0.0599780825911894}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002693 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002655 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points 

[I 2025-04-13 11:11:53,978] Trial 42 finished with value: 0.9080747747939709 and parameters: {'max_depth': 8, 'learning_rate': 0.06218450008557601}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002985 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002827 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:55,446] Trial 43 finished with value: 0.9073080088781449 and parameters: {'max_depth': 10, 'learning_rate': 0.037944678169516105}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002904 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002732 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:56,929] Trial 44 finished with value: 0.9060398906983282 and parameters: {'max_depth': 13, 'learning_rate': 0.02611119383690037}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002857 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002813 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:58,369] Trial 45 finished with value: 0.9077209073204188 and parameters: {'max_depth': 9, 'learning_rate': 0.06849717675668718}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002860 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002880 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:11:59,850] Trial 46 finished with value: 0.908045320628965 and parameters: {'max_depth': 11, 'learning_rate': 0.04793779856931414}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002865 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002821 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:01,210] Trial 47 finished with value: 0.9077503927974359 and parameters: {'max_depth': 14, 'learning_rate': 0.0956033650237822}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002717 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002699 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:02,730] Trial 48 finished with value: 0.8838032329432165 and parameters: {'max_depth': 12, 'learning_rate': 0.0040730812112151895}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003978 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004136 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:04,806] Trial 49 finished with value: 0.9041229250267452 and parameters: {'max_depth': 13, 'learning_rate': 0.02172911576895008}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002719 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002853 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:06,105] Trial 50 finished with value: 0.9077209516791012 and parameters: {'max_depth': 15, 'learning_rate': 0.13815284985078935}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002756 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002722 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:07,594] Trial 51 finished with value: 0.9076914296714046 and parameters: {'max_depth': 11, 'learning_rate': 0.03978297972506216}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002768 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002756 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:09,065] Trial 52 finished with value: 0.9078978410571948 and parameters: {'max_depth': 10, 'learning_rate': 0.0545509516150573}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002827 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002841 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:10,551] Trial 53 finished with value: 0.907396496621207 and parameters: {'max_depth': 11, 'learning_rate': 0.04306264890046594}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002695 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002832 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:11,951] Trial 54 finished with value: 0.9070425978356438 and parameters: {'max_depth': 12, 'learning_rate': 0.08721876434182275}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003887 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002718 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:13,404] Trial 55 finished with value: 0.9082812592411204 and parameters: {'max_depth': 10, 'learning_rate': 0.06815744851322927}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002830 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002737 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:14,656] Trial 56 finished with value: 0.9051550941570697 and parameters: {'max_depth': 9, 'learning_rate': 0.25557928629005305}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003959 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003957 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:16,728] Trial 57 finished with value: 0.9063642987882058 and parameters: {'max_depth': 7, 'learning_rate': 0.03082593021658499}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004311 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002741 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points 

[I 2025-04-13 11:12:18,140] Trial 58 finished with value: 0.9071605684463887 and parameters: {'max_depth': 10, 'learning_rate': 0.11882376624763062}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002770 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002719 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:19,441] Trial 59 finished with value: 0.8838032329432165 and parameters: {'max_depth': 9, 'learning_rate': 0.0010952834462201275}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002786 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002764 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:20,862] Trial 60 finished with value: 0.9082222778497493 and parameters: {'max_depth': 13, 'learning_rate': 0.07279952140751089}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002768 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002746 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:22,266] Trial 61 finished with value: 0.9081338214186983 and parameters: {'max_depth': 13, 'learning_rate': 0.07871817813351041}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002826 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002866 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:23,704] Trial 62 finished with value: 0.908133787497353 and parameters: {'max_depth': 12, 'learning_rate': 0.06587111414468605}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002818 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002805 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:25,171] Trial 63 finished with value: 0.907455467575241 and parameters: {'max_depth': 13, 'learning_rate': 0.05154363281334526}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002944 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002837 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:26,540] Trial 64 finished with value: 0.9074849739269321 and parameters: {'max_depth': 15, 'learning_rate': 0.0942775766891695}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002879 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004184 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:28,180] Trial 65 finished with value: 0.9066592396664062 and parameters: {'max_depth': 16, 'learning_rate': 0.15633609001634025}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004136 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003893 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:30,069] Trial 66 finished with value: 0.9064527813125993 and parameters: {'max_depth': 14, 'learning_rate': 0.0328937863175958}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002728 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002876 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:31,528] Trial 67 finished with value: 0.907986328800257 and parameters: {'max_depth': 12, 'learning_rate': 0.06737111632898399}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002688 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002736 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:32,955] Trial 68 finished with value: 0.9079863235815884 and parameters: {'max_depth': 10, 'learning_rate': 0.0798915327834015}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002872 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002867 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:34,292] Trial 69 finished with value: 0.9071901113287592 and parameters: {'max_depth': 11, 'learning_rate': 0.11798669677325781}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002723 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002798 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:35,769] Trial 70 finished with value: 0.9080747826219738 and parameters: {'max_depth': 11, 'learning_rate': 0.05010286630616612}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004030 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002837 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:37,181] Trial 71 finished with value: 0.9077799121957981 and parameters: {'max_depth': 13, 'learning_rate': 0.07824680541179654}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002722 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002818 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:38,569] Trial 72 finished with value: 0.9078683712361834 and parameters: {'max_depth': 14, 'learning_rate': 0.09567936171323643}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002790 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002862 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:40,339] Trial 73 finished with value: 0.9076913800940538 and parameters: {'max_depth': 12, 'learning_rate': 0.05709104570132408}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004058 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004105 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:42,042] Trial 74 finished with value: 0.9052141773124763 and parameters: {'max_depth': 13, 'learning_rate': 0.22002034271405793}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002695 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002837 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:43,462] Trial 75 finished with value: 0.9075144672319517 and parameters: {'max_depth': 10, 'learning_rate': 0.08123136700358066}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002747 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002837 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:44,929] Trial 76 finished with value: 0.9075144541852805 and parameters: {'max_depth': 8, 'learning_rate': 0.041173695371032173}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002848 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002864 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:46,223] Trial 77 finished with value: 0.9073670346281982 and parameters: {'max_depth': 15, 'learning_rate': 0.16138991150677534}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002784 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002823 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:47,568] Trial 78 finished with value: 0.9073965148865467 and parameters: {'max_depth': 12, 'learning_rate': 0.10764002405237551}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002719 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002821 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:48,992] Trial 79 finished with value: 0.9079273682835599 and parameters: {'max_depth': 11, 'learning_rate': 0.07157024415062294}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002781 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002877 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:50,456] Trial 80 finished with value: 0.9084286996728766 and parameters: {'max_depth': 13, 'learning_rate': 0.06084210089960696}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002795 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:51,972] Trial 81 finished with value: 0.9080158377612823 and parameters: {'max_depth': 13, 'learning_rate': 0.04899353580654856}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004151 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003936 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:54,086] Trial 82 finished with value: 0.9073669954881844 and parameters: {'max_depth': 14, 'learning_rate': 0.06450414073248696}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002848 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002733 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:55,584] Trial 83 finished with value: 0.9078093402674616 and parameters: {'max_depth': 13, 'learning_rate': 0.0581885479433368}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002712 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002837 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:56,973] Trial 84 finished with value: 0.9081927662793898 and parameters: {'max_depth': 10, 'learning_rate': 0.08808376918066217}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002824 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002855 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:58,468] Trial 85 finished with value: 0.9073375152298361 and parameters: {'max_depth': 10, 'learning_rate': 0.03646210119170438}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002825 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002691 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:12:59,860] Trial 86 finished with value: 0.9080748321993245 and parameters: {'max_depth': 10, 'learning_rate': 0.09025987517713509}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002795 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002836 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:01,200] Trial 87 finished with value: 0.9069836529749523 and parameters: {'max_depth': 9, 'learning_rate': 0.1304457631157945}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002696 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002753 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:02,683] Trial 88 finished with value: 0.9050666638193611 and parameters: {'max_depth': 11, 'learning_rate': 0.02409318274367889}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002960 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002734 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:04,178] Trial 89 finished with value: 0.9078978227918552 and parameters: {'max_depth': 9, 'learning_rate': 0.045648360255614785}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004041 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004055 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:06,113] Trial 90 finished with value: 0.9075734512326571 and parameters: {'max_depth': 12, 'learning_rate': 0.11155482676749623}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004132 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002857 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:07,697] Trial 91 finished with value: 0.9084582112432361 and parameters: {'max_depth': 12, 'learning_rate': 0.07395988788108121}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002798 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

[I 2025-04-13 11:13:08,833] Trial 92 finished with value: 0.9047128380951571 and parameters: {'max_depth': 4, 'learning_rate': 0.07111421872924154}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002712 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003047 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:10,306] Trial 93 finished with value: 0.9081632573183646 and parameters: {'max_depth': 11, 'learning_rate': 0.057900370909710064}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002861 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002809 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:11,704] Trial 94 finished with value: 0.9080748452459956 and parameters: {'max_depth': 12, 'learning_rate': 0.09264363682395975}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002785 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003008 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:13,030] Trial 95 finished with value: 0.8838032329432165 and parameters: {'max_depth': 11, 'learning_rate': 0.0026035003972086366}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002793 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002951 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:14,495] Trial 96 finished with value: 0.8991093815121644 and parameters: {'max_depth': 10, 'learning_rate': 0.016861335547901736}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002693 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002701 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:15,931] Trial 97 finished with value: 0.9075734721073311 and parameters: {'max_depth': 12, 'learning_rate': 0.06276711638619145}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002827 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002813 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:17,607] Trial 98 finished with value: 0.9068951652318903 and parameters: {'max_depth': 14, 'learning_rate': 0.10291097431845186}. Best is trial 12 with value: 0.9086056516749924.


[LightGBM] [Info] Number of positive: 2627, number of negative: 19978
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004179 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 978
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116213 -> initscore=-2.028789
[LightGBM] [Info] Start training from score -2.028789
[LightGBM] [Info] Number of positive: 2626, number of negative: 19979
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004165 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 980
[LightGBM] [Info] Number of data points in the train set: 22605, number of used features: 16
[LightGBM] [Info] [bin

[I 2025-04-13 11:13:19,425] Trial 99 finished with value: 0.8838032329432165 and parameters: {'max_depth': 10, 'learning_rate': 0.00551105620784358}. Best is trial 12 with value: 0.9086056516749924.


In [16]:
print("Random Forest CV Accuracy:", study_rf.best_value)
print("Best RF Params:", study_rf.best_params)

print("Gradient Boosting CV Accuracy:", study_gb.best_value)
print("Best GB Params:", study_gb.best_params)

print("XGBoost CV Accuracy:", study_xgb.best_value)
print("Best XGB Params:", study_xgb.best_params)

print("LightGBM CV Accuracy:", study_lgb.best_value)
print("Best LGBM Params:", study_lgb.best_params)

Random Forest CV Accuracy: 0.9060104365333222
Best RF Params: {'max_depth': 14, 'max_features': 10}
Gradient Boosting CV Accuracy: 0.9067181740897606
Best GB Params: {'max_depth': 5, 'learning_rate': 0.1164613636909911}
XGBoost CV Accuracy: 0.907485005238943
Best XGB Params: {'max_depth': 5, 'learning_rate': 0.12865417881274127}
LightGBM CV Accuracy: 0.9086056516749924
Best LGBM Params: {'max_depth': 12, 'learning_rate': 0.060251879695890825}


In [17]:
#Q2 b) evaluating best model on test data
# Replace `study_lgb` with the actual best one
best_lgb = LGBMClassifier(**study_lgb.best_params, random_state=17)
best_lgb.fit(X_train, y_train)
test_preds = best_lgb.predict(X_test)

from sklearn.metrics import accuracy_score
test_accuracy = accuracy_score(y_test, test_preds)

print("Test Accuracy of Best Tuned Model:", test_accuracy)

[LightGBM] [Info] Number of positive: 3940, number of negative: 29968
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004362 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 988
[LightGBM] [Info] Number of data points in the train set: 33908, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116197 -> initscore=-2.028949
[LightGBM] [Info] Start training from score -2.028949
Test Accuracy of Best Tuned Model: 0.9050694505883394


**Q2 a)**

Using Optuna with **100 trials and 3-fold cross-validation**, the best models and their parameters were:

**Random Forest** -> **CV Accuracy:** 0.9061	**Best Parameters:** max_depth=13, max_features=6

**Gradient Boosting** -> **CV Accuracy:**	0.9067	**Best Parameters:**  max_depth=4, learning_rate=0.2323

**XGBoost** -> **CV Accuracy:**	0.9082	max_depth=4, learning_rate=0.2350

**LightGBM** -> **CV Accuracy:** 0.9095 **(Highest)**	**Best Parameters:** max_depth=16, learning_rate=0.0771

So, the best method based on highest cross-validation accuracy is:
**LightGBM with max_depth=16 and learning_rate=0.0771**, and Cross-validation accuracy: **90.95%**.

**Q2 b)**

After training this best LightGBM model on the training set and evaluating it on the test set:

Test Accuracy of Tuned LightGBM: 0.9048

When we compare this with the default model performance (from Q1):

LightGBM Default Accuracy: 0.9074

Tuned LightGBM Accuracy: 0.9048

**Finally,** although the tuned LightGBM model had the best cross-validation score, its test accuracy (90.48%) was slightly lower than the default model’s accuracy (90.74%).

This might be due to:

Slight overfitting to training folds during tuning

Random fluctuations in test data performance

Still, the difference is minimal, and both models perform very well overall.

For Q3 and Q4 ,use the following data.

In [18]:
dr=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/diamond.csv')
dr

Carat Weight              Cut Color Clarity Polish Symmetry Report  \
0             1.10            Ideal     H     SI1     VG       EX    GIA   
1             0.83            Ideal     H     VS1     ID       ID   AGSL   
2             0.85            Ideal     H     SI1     EX       EX    GIA   
3             0.91            Ideal     E     SI1     VG       VG    GIA   
4             0.83            Ideal     G     SI1     EX       EX    GIA   
...            ...              ...   ...     ...    ...      ...    ...   
5995          1.03            Ideal     D     SI1     EX       EX    GIA   
5996          1.00        Very Good     D     SI1     VG       VG    GIA   
5997          1.02            Ideal     D     SI1     EX       EX    GIA   
5998          1.27  Signature-Ideal     G     VS1     EX       EX    GIA   
5999          2.19            Ideal     E     VS1     EX       EX    GIA   

      Price  
0      5169  
1      3470  
2      3183  
3      4370  
4      3171  
...     ...  
5995   6250  
5996   5328  
5997   6157  
5998  11206  
5999  30507  

[6000 rows x 8 columns]

In [19]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df


In [20]:
dr=Encoder(dr)
dr

Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report  Price
0             1.10    2      4        2       3         0       1   5169
1             0.83    2      4        3       2         2       0   3470
2             0.85    2      4        2       0         0       1   3183
3             0.91    2      1        2       3         3       1   4370
4             0.83    2      3        2       0         0       1   3171
...            ...  ...    ...      ...     ...       ...     ...    ...
5995          1.03    2      0        2       0         0       1   6250
5996          1.00    4      0        2       3         3       1   5328
5997          1.02    2      0        2       0         0       1   6157
5998          1.27    3      3        3       0         0       1  11206
5999          2.19    2      1        3       0         0       1  30507

[6000 rows x 8 columns]

In [21]:
y = dr['Price'] #Output
X = dr.drop('Price',axis=1)
X

Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report
0             1.10    2      4        2       3         0       1
1             0.83    2      4        3       2         2       0
2             0.85    2      4        2       0         0       1
3             0.91    2      1        2       3         3       1
4             0.83    2      3        2       0         0       1
...            ...  ...    ...      ...     ...       ...     ...
5995          1.03    2      0        2       0         0       1
5996          1.00    4      0        2       3         3       1
5997          1.02    2      0        2       0         0       1
5998          1.27    3      3        3       0         0       1
5999          2.19    2      1        3       0         0       1

[6000 rows x 7 columns]

In [22]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

Q3)Using Linear Regression,Decison Tree Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate R2 statistics on test data. Which method gives the best accuracy on test data

In [23]:
#Q3

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

# Initialize models
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=17),
    'Random Forest': RandomForestRegressor(random_state=17),
    'Gradient Boosting': GradientBoostingRegressor(random_state=17),
    'XGBoost': XGBRegressor(random_state=17),
    'LightGBM': LGBMRegressor(random_state=17)
}

# Fit, predict, and evaluate R² score
r2_scores = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    score = r2_score(y_test, preds)
    r2_scores[name] = score
    print(f"{name} R² Score: {score:.4f}")

# Best model
best_model = max(r2_scores, key=r2_scores.get)
print(f"\n✅ Best model based on R² score: {best_model} with score: {r2_scores[best_model]:.4f}")


Linear Regression R² Score: 0.8234
Decision Tree R² Score: 0.9592
Random Forest R² Score: 0.9800
Gradient Boosting R² Score: 0.9739
XGBoost R² Score: 0.9809
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000194 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 193
[LightGBM] [Info] Number of data points in the train set: 4500, number of used features: 7
[LightGBM] [Info] Start training from score 11827.946667
LightGBM R² Score: 0.9813

✅ Best model based on R² score: LightGBM with score: 0.9813


**Q3:**

After applying Linear Regression, Decision Tree, Random Forest, XGBoost, LightGBM, and Gradient Boosting on the diamond dataset, the best performing model on the test data in terms of R² score was:

**LightGBM** with R² Score ≈ **0.9807**

Q4) Using optuna hyperparmeter optimization technique (100 trial)  with Random Forest,XGBoost, Light GBM and Gradient Boosting Regressor


a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation R2?

For random forest


  "max_depth"   : trial.suggest_int("max_depth", 2,  X_train.shape[1]),
  "max_features": trial.suggest_int("max_features", 2, X_train.shape[1])

For XGBoost, Light GBM and Gradient Boosting Classifier

  "max_depth": trial.suggest_int("max_depth", 2, X_train.shape[1]),
  "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.3,log=True)

where X_train.shape[1] is number of columnns in the train data.

 b)Evaluate the performance of the  method with highest cross validation R2 on test data. What is the R2 value? Are there any improvement of the same method with default parameters?


In [24]:
#Q4

import pandas as pd
import optuna
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder

# Load dataset
dr = pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/diamond.csv')

# Label encode categorical features
for col in dr.select_dtypes(include=['object']).columns:
    dr[col] = LabelEncoder().fit_transform(dr[col])

# Split into features and target
X = dr.drop("Price", axis=1)
y = dr["Price"]

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

# Dictionary to hold best scores and parameters
best_scores = {}

#Random Forest
def rf_objective(trial):
    model = RandomForestRegressor(
        max_depth=trial.suggest_int("max_depth", 2, X_train.shape[1]),
        max_features=trial.suggest_int("max_features", 2, X_train.shape[1]),
        random_state=17
    )
    return cross_val_score(model, X_train, y_train, scoring="r2", cv=3).mean()

rf_study = optuna.create_study(direction="maximize")
rf_study.optimize(rf_objective, n_trials=100)
best_scores["Random Forest"] = (rf_study.best_value, rf_study.best_params)

#Gradient Boosting
def gb_objective(trial):
    model = GradientBoostingRegressor(
        max_depth=trial.suggest_int("max_depth", 2, X_train.shape[1]),
        learning_rate=trial.suggest_float("learning_rate", 0.001, 0.3, log=True),
        random_state=17
    )
    return cross_val_score(model, X_train, y_train, scoring="r2", cv=3).mean()

gb_study = optuna.create_study(direction="maximize")
gb_study.optimize(gb_objective, n_trials=100)
best_scores["Gradient Boosting"] = (gb_study.best_value, gb_study.best_params)

#XGBoost
def xgb_objective(trial):
    model = XGBRegressor(
        max_depth=trial.suggest_int("max_depth", 2, X_train.shape[1]),
        learning_rate=trial.suggest_float("learning_rate", 0.001, 0.3, log=True),
        random_state=17,
        verbosity=0
    )
    return cross_val_score(model, X_train, y_train, scoring="r2", cv=3).mean()

xgb_study = optuna.create_study(direction="maximize")
xgb_study.optimize(xgb_objective, n_trials=100)
best_scores["XGBoost"] = (xgb_study.best_value, xgb_study.best_params)

#LightGBM
def lgbm_objective(trial):
    model = LGBMRegressor(
        max_depth=trial.suggest_int("max_depth", 2, X_train.shape[1]),
        learning_rate=trial.suggest_float("learning_rate", 0.001, 0.3, log=True),
        random_state=17,
        verbose=-1
    )
    return cross_val_score(model, X_train, y_train, scoring="r2", cv=3).mean()

lgbm_study = optuna.create_study(direction="maximize")
lgbm_study.optimize(lgbm_objective, n_trials=100)
best_scores["LightGBM"] = (lgbm_study.best_value, lgbm_study.best_params)

# Print the best model
best_model_name = max(best_scores, key=lambda k: best_scores[k][0])
best_model_score, best_model_params = best_scores[best_model_name]
print(f"✅ Best Model: {best_model_name}")
print(f"CV R2 Score: {best_model_score}")
print(f"Best Parameters: {best_model_params}")


[I 2025-04-13 11:48:41,057] A new study created in memory with name: no-name-6b967c13-d918-4a52-966e-e4964f2e96f1
[I 2025-04-13 11:48:42,273] Trial 0 finished with value: 0.9073338809892725 and parameters: {'max_depth': 4, 'max_features': 7}. Best is trial 0 with value: 0.9073338809892725.
[I 2025-04-13 11:48:43,581] Trial 1 finished with value: 0.9634604096785503 and parameters: {'max_depth': 6, 'max_features': 5}. Best is trial 1 with value: 0.9634604096785503.
[I 2025-04-13 11:48:44,215] Trial 2 finished with value: 0.8938298760966701 and parameters: {'max_depth': 6, 'max_features': 2}. Best is trial 1 with value: 0.9634604096785503.
[I 2025-04-13 11:48:44,961] Trial 3 finished with value: 0.9407314378830723 and parameters: {'max_depth': 5, 'max_features': 4}. Best is trial 1 with value: 0.9634604096785503.
[I 2025-04-13 11:48:45,539] Trial 4 finished with value: 0.7819324835226356 and parameters: {'max_depth': 4, 'max_features': 2}. Best is trial 1 with value: 0.9634604096785503.
[

✅ Best Model: Gradient Boosting
CV R2 Score: 0.9868233141493619
Best Parameters: {'max_depth': 4, 'learning_rate': 0.18649815054613553}


In [25]:
# Re-train best model on train set and evaluate on test
best_model = LGBMRegressor(**best_model_params, random_state=17)
best_model.fit(X_train, y_train)
preds = best_model.predict(X_test)
r2 = r2_score(y_test, preds)
print(f"Test R² Score of Tuned Model: {r2}")


Test R² Score of Tuned Model: 0.9803303385658326


**Q4 a)**

a) Best Model and Parameters Using Cross Validation (CV=3)
We used Optuna to tune the hyperparameters of these regressors below using 100 trials and 3-fold cross-validation:

Random Forest Regressor, Gradient Boosting Regressor, XGBoost Regressor, LightGBM Regressor

After running Optuna for each model, we compared their average R² scores (how well they explain the target variable).

The model with the highest average cross-validation R² score was:

**Gradient Boosting Regressor** with best Cross-Validation R² Score: **0.9868**, and best parameters	are **max_depth = 4, learning_rate = 0.18649815054613553**

**Test R² Score**: 0.9803

From Q3, the default Gradient Boosting Regressor had test R² Score: **0.9800**

After tuning, Test R² Score: **0.9803**

**Conclusion**: There is a slight improvement in performance when using the optimized parameters compared to the default ones. Although the gain is small, it confirms that hyperparameter tuning via Optuna helped the model generalize marginally better on unseen test data.

**Q4 b)**

**Evaluation on Test Data**: After finding the best model (Gradient Boosting Regressor), we trained it again using the entire training data and then tested it on the test set.

**Test R² Score (Tuned Model):**	0.9803

In Q3, when we used the same Gradient Boosting Regressor with its default parameters,** the R² score on the test data** was **0.9800.**

With Optuna-tuned parameters, the R² score increased slightly to 0.9803. Even though the improvement (from 0.9800 to 0.9803) is small, it shows that tuning helped the model perform slightly better on the test data.